language: node_js

node_js:
  - node

branches:
  only:
    - master

cache: yarn

script:
  - yarn lint
  - yarn test
  - yarn deploy:ci

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
