service: sls-api

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  cfLogs: true
  logRetentionInDays: 7
  versionFunctions: false
  timeout: 20
  logs:
    restApi: true
  environment:
    STAGE: ${opt:stage, 'dev'}

functions:
  graphql:
    name: ${self:provider.stage}-GraphQLApi
    description: GraphQL API of Brokalys.
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-aws-alerts
  - serverless-offline

custom:
  customDomain:
    domainName: api.brokalys.com
    stage: prod
    certificateName: '*.brokalys.com'
    createRoute53Record: true
    endpointType: edge

  alerts:
    stages:
      - prod
    topics:
      alarm:
        topic: ${self:provider.stage}-${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: matiss@brokalys.com
      ok:
        topic: ${self:provider.stage}-${self:service}-alerts-ok
        notifications:
          - protocol: email
            endpoint: matiss@brokalys.com
    definitions:
      functionErrors:
        description: 'SLS API has an error that needs to be fixed'
        treatMissingData: notBreaching
    alarms:
      - functionErrors

  serverless-offline:
    useChildProcesses: true

  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk

        # These peerDependencies are not actually used in the project, but are
        # breaking SLS deployments
        - mssql
        - mysql2
        - pg
        - sqlite3
    packager: yarn
