service: sls-api

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  cfLogs: true
  logRetentionInDays: 7
  versionFunctions: false
  environment:
    DB_HOST: ${file(serverless.env.yml):DB_HOST, env:DB_HOST}
    DB_DATABASE: ${file(serverless.env.yml):DB_DATABASE, env:DB_DATABASE}
    DB_USERNAME: ${file(serverless.env.yml):DB_USERNAME, env:DB_USERNAME}
    DB_PASSWORD: ${file(serverless.env.yml):DB_PASSWORD, env:DB_PASSWORD}
    DB_PINGER_DATABASE: ${file(serverless.env.yml):DB_PINGER_DATABASE, env:DB_PINGER_DATABASE}
    DB_CACHE_DATABASE: ${file(serverless.env.yml):DB_CACHE_DATABASE, env:DB_CACHE_DATABASE}
    MAILGUN_API_KEY: ${file(serverless.env.yml):MAILGUN_API_KEY, env:MAILGUN_API_KEY}
    MAILGUN_DOMAIN: ${file(serverless.env.yml):MAILGUN_DOMAIN, env:MAILGUN_DOMAIN}
    MAILGUN_TO_EMAIL: ${file(serverless.env.yml):MAILGUN_TO_EMAIL, env:MAILGUN_TO_EMAIL}
    STAGE: ${opt:stage, 'dev'}

functions:
  graphql:
    name: ${self:provider.stage}-GraphQLApi
    description: GraphQL API of Brokalys.
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-aws-alerts
  - serverless-offline

custom:
  customDomain:
    domainName: api.brokalys.com
    stage: prod
    certificateName: '*.brokalys.com'
    createRoute53Record: true
    endpointType: edge

  alerts:
    stages:
      - prod
    topics:
      alarm:
        topic: ${self:provider.stage}-${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: matiss@brokalys.com
    definitions:
      functionThrottles:
        treatMissingData: notBreaching
      functionErrors:
        treatMissingData: notBreaching
      functionInvocations:
        treatMissingData: notBreaching
      functionDuration:
        threshold: 4000
        treatMissingData: notBreaching
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

  webpack:
    includeModules: true
    packager: yarn
