service: sls-map-api

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  # timeout: 1
  cfLogs: true
  versionFunctions: false
  environment:
    DB_HOST: ${file(serverless.env.yml):DB_HOST, env:DB_HOST}
    DB_DATABASE: ${file(serverless.env.yml):DB_DATABASE, env:DB_DATABASE}
    DB_USERNAME: ${file(serverless.env.yml):DB_USERNAME, env:DB_USERNAME}
    DB_PASSWORD: ${file(serverless.env.yml):DB_PASSWORD, env:DB_PASSWORD}

functions:
  graphql:
    name: GraphQLApi
    description: GraphQL API of Brokalys.
    handler: src/handler.graphqlHandler
    events:
    # - http:
    #     path: graphql
    #     method: post
    #     cors: true
    - http:
        path: graphql
        method: get


plugins:
  - serverless-domain-manager
  - serverless-plugin-aws-alerts
  - serverless-offline

custom:
  customDomain:
    domainName: api.brokalys.com
    certificateName: '*.brokalys.com'
    createRoute53Record: true
    endpointType: edge

  alerts:
    topics:
      alarm:
        topic: ${self:service}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: matiss@brokalys.com
    definitions:
      functionThrottles:
        treatMissingData: notBreaching
      functionErrors:
        treatMissingData: notBreaching
      functionInvocations:
        treatMissingData: notBreaching
      functionDuration:
        threshold: 1500
        treatMissingData: notBreaching
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
