exports.seed = function (knex) {
  return knex('properties')
    .del()
    .then(function () {
      return knex('properties').insert([
        {
          id: 1,
          source: 'ss.lv',
          url:
            'https://www.ss.com/msg/lv/real-estate/flats/aizkraukle-and-reg/aiviekstes-pag/aghfx.html',
          category: 'apartment',
          type: 'rent',
          rent_type: 'monthly',
          price: 100,
          lat: 56.1,
          lng: 24.9,
          location_classificator: 'latvia-riga-agenskalns',
          area: 90,
          floor: 2,
          calc_price_per_sqm: 1.11,
          building_id: 1,
          created_at: '2021-01-02T00:00:00.000Z',
          published_at: '2021-04-12T19:47:30.000Z',
        },
        {
          id: 2,
          source: 'ss.lv',
          url:
            'https://www.ss.lv/msg/lv/real-estate/flats/riga/bolderaya/cceeb.html',
          category: 'apartment',
          type: 'rent',
          rent_type: 'monthly',
          price: 200,
          lat: 56.1,
          lng: 24.9,
          location_classificator: 'latvia-riga-agenskalns',
          building_id: 1,
          created_at: '2019-04-02T00:00:00.000Z',
          published_at: '2021-04-12T19:47:30.000Z',
        },
        {
          id: 3,
          source: 'ss.lv',
          url:
            'https://www.ss.com/msg/lv/real-estate/homes-summer-residences/tukums-and-reg/engures-pag/hhjbf.html',
          category: 'house',
          type: 'rent',
          rent_type: 'monthly',
          price: 300,
          location_classificator: 'latvia-riga-mezciems',
          building_id: 2,
          created_at: '2020-01-02T00:00:00.000Z',
          published_at: '2021-04-12T19:47:30.000Z',
        },
        {
          id: 4,
          source: 'city24.lv',
          category: 'house',
          type: 'rent',
          rent_type: 'monthly',
          price: 400,
          location_classificator: 'latvia-riga-mezciems',
          building_id: 4,
          foreign_id: 'id111',
        },
        {
          id: 5,
          source: 'city24.lv',
          category: 'house',
          type: 'rent',
          rent_type: 'monthly',
          price: 400,
          location_classificator: 'latvia-riga-mezciems',
          building_id: 4,
          foreign_id: 'id999',
        },
        {
          id: 6,
          source: 'ss.lv',
          category: 'house',
          type: 'sell',
          rent_type: null,
          price: 400,
          foreign_id: 'id111',
          location_classificator: 'latvia-riga-mezciems',
          building_id: 4,
          created_at: '2020-01-02T00:00:00.000Z',
          published_at: '2021-04-12T19:47:30.000Z',
        },
        {
          id: 7,
          source: 'inch.lv',
          url: 'https://inch.lv',
          category: 'land',
          type: 'sell',
          rent_type: null,
          price: 60000,
          location_classificator: 'latvia-riga-vecpilseta',
          foreign_id: '10001',
          building_id: 5,
        },
        {
          id: 8,
          source: 'inch.lv',
          url: 'https://inch.lv',
          category: 'house',
          type: 'sell',
          rent_type: null,
          price: 400000,
          location_classificator: 'latvia-riga-vecpilseta',
          foreign_id: '10009',
          building_id: 5,
        },
        {
          id: 9,
          source: 'mm-lv',
          url: 'https://mm.lv',
          category: 'house',
          type: 'sell',
          rent_type: null,
          price: 400000,
          foreign_id: 'id111',
          building_id: 5,
        },
        {
          id: 10,
          source: 'mm-lv',
          url: 'https://mm.lv/other',
          category: 'house',
          type: 'sell',
          rent_type: null,
          price: 400000,
          foreign_id: 'id222',
          building_id: 5,
        },
      ]);
    });
};
