export default {
  id: (item) => item.id_hash,
  email: (item) => item.email,
  category: (item) => JSON.parse(item.categories)[0].toUpperCase(),
  type: (item) => JSON.parse(item.types)[0].toUpperCase(),
  price_min: (item) => item.price_min,
  price_max: (item) => item.price_max,
  price_type: (item) => item.price_type.toUpperCase(),
  region: (item) => item.region,
  rooms_min: (item) => item.rooms_min,
  rooms_max: (item) => item.rooms_max,
  area_m2_min: (item) => item.area_m2_min,
  area_m2_max: (item) => item.area_m2_max,
  frequency: (item) => item.frequency.toUpperCase(),
  comments: (item) => item.comments,
  marketing: (item) => item.marketing,
  created_at: (item) => item.created_at,
  unsubscribed_at: (item) => item.unsubscribed_at,
  unsubscribe_key: (item) => item.unsubscribe_key,
};
